operator: operators.ExternalTable
source_objects:
  - "payments-processed/product_data/*"
destination_project_dataset_table: "payments.product_data"
skip_leading_rows: 1
schema_fields:
  - name: participant_id
    type: STRING
  - name: product_id
    type: STRING
  - name: product_code
    type: STRING
  - name: product_description
    type: STRING
  - name: product_type
    type: STRING  # (Capping, Discount)
  - name: activation_type
    type: STRING  # (Customer, Card)
  - name: product_status
    type: STRING  # (Active, Inactive)
  - name: created_date
    type: TIMESTAMP
  - name: capping_type
    type: STRING  # (Daily_cap, Weekly_cap, Multiday_cap, Timebased_cap)
  - name: multi_operator
    type: BOOL
  - name: capping_start_time
    type: TIME
  - name: capping_end_time
    type: TIME
  - name: rules_transaction_types
    type: STRING  # (Autoscan, Flat, Variable)
  - name: rules_default_limit
    type: STRING
  - name: rules_max_fare_value
    type: STRING
  - name: scheduled_start_date_time
    type: DATE
  - name: scheduled_end_date_time
    type: DATE
  - name: all_day
    type: BOOL
  - name: weekly_cap_start_day
    type: STRING  # (Monday, Sunday)
  - name: number_of_days_in_cap_window
    type: FLOAT64
  - name: capping_duration
    type: FLOAT64
  - name: number_of_transfer
    type: INTEGER
  - name: capping_time_zone
    type: STRING
  - name: capping_overlap
    type: TIME
  - name: capping_application_level
    type: STRING  # (Customer, Card)
  - name: calitp_extracted_at
    type: DATE
