name: Lint and style checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v3.0.0
  # We have to use the action rather than pre-commit because of https://github.com/crate-ci/typos/issues/347
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crate-ci/typos@master
