name: move DAGs to GCS folder

on:
  push:
    paths:
      - 'airflow/**'
  pull_request:
    paths:
      - 'airflow/**'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install python packages
      run: |
        pip install jinja2==2.11.3 PyYAML==5.4.1 jsonschema==3.2.0 pandas==1.1.4
    # Create the secrets.csv from the contents of the `AGENCY_SECRETS` environment variable / GitHub
    # repository secret. The contents of this environment variable should be directly copied from
    # the contents of a filled-out ./airflow/data/example-secrets.csv file.
    - name: Create csv file with API keys
      run: echo -e "$AGENCY_SECRETS" > ./airflow/data/secrets.csv
      env:
        AGENCY_SECRETS: ${{ secrets.AGENCY_SECRETS }}
    # Populate the secrets within the agencies.yml file
    - name: Fill in agencies.yml API keys
      run: |
        python script/agencies_convert.py \
          './airflow/data/agencies.yml' \
          './airflow/data/agencies.filled.yml' \
          './airflow/data/secrets.csv'
    - name: Validate agencies.yml
      run: |
        python script/agencies_validate.py \
          './airflow/data/agencies.filled.yml' \
          './airflow/data/schema_agencies_entry.yml'

    - if: ${{ github.repository == 'cal-itp/data-infra' }}
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - if: ${{ github.repository == 'cal-itp/data-infra' }}
      name: Setup kubeconfig
      env:
        CLOUDSDK_CORE_PROJECT: cal-itp-data-infra
      run: |
        source "$GITHUB_WORKSPACE/kubernetes/gke/config-cluster.sh"
        gcloud container clusters get-credentials "$GKE_NAME" --region "$GKE_REGION"

    # push to prod services when merging into main branch
    - name: Push agencies data to google cloud and prod services
      if: ${{ github.repository == 'cal-itp/data-infra' && github.ref == 'refs/heads/main' }}
      run: |
        # BEGIN AIRFLOW1 ENVIRONMENT
        gsutil -m rsync -d -c -r airflow/dags gs://us-west2-calitp-airflow-pro-332827a9-bucket/dags
        gsutil -m rsync -d -c -r airflow/plugins gs://us-west2-calitp-airflow-pro-332827a9-bucket/plugins
        gsutil -m rsync -d -c -r airflow/data gs://us-west2-calitp-airflow-pro-332827a9-bucket/data
        # replace agencies.yml with filled in template for airflow
        gsutil -m cp airflow/data/agencies.yml gs://us-west2-calitp-airflow-pro-332827a9-bucket/data/agencies_raw.yml
        gsutil -m cp airflow/data/agencies.filled.yml gs://us-west2-calitp-airflow-pro-332827a9-bucket/data/agencies.yml
        # END AIRFLOW1 ENVIRONMENT
        # BEGIN AIRFLOW2 ENVIRONMENT
        gsutil -m rsync -d -c -r airflow/dags gs://us-west2-calitp-airflow2-pr-91e4038b-bucket/dags
        gsutil -m rsync -d -c -r airflow/plugins gs://us-west2-calitp-airflow2-pr-91e4038b-bucket/plugins
        gsutil -m rsync -d -c -r airflow/data gs://us-west2-calitp-airflow2-pr-91e4038b-bucket/data
        # replace agencies.yml with filled in template for airflow
        gsutil -m cp airflow/data/agencies.yml gs://us-west2-calitp-airflow2-pr-91e4038b-bucket/data/agencies_raw.yml
        gsutil -m cp airflow/data/agencies.filled.yml gs://us-west2-calitp-airflow2-pr-91e4038b-bucket/data/agencies.yml
        # END AIRFLOW2 ENVIRONMENT
        # replace agencies.yml with filled in template for gtfs rt extract service
        kubectl apply -f - <<EOF
        apiVersion: v1
        kind: Secret
        metadata:
          name: agencies-data
          namespace: gtfs-rt
        data:
          data_agencies.yaml: $(base64 -w0 airflow/data/agencies.filled.yml)
        EOF
        kubectl -n gtfs-rt rollout restart deployments/gtfs-rt-archive

    # push to preprod services when merging to other branches
    - name: Push agencies data to preprod services
      if: ${{ github.repository == 'cal-itp/data-infra' && github.ref != 'refs/heads/main' }}
      run: |
        kubectl apply -f - <<EOF
        apiVersion: v1
        kind: Secret
        metadata:
          name: agencies-data
          namespace: gtfs-rt-preprod
        data:
          data_agencies.yaml: $(base64 -w0 airflow/data/agencies.filled.yml)
        EOF
        kubectl -n gtfs-rt-preprod rollout restart deployments/gtfs-rt-archive
