name: Visualize dbt DAG changes

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/visualize-warehouse-changes.yml'
      - 'warehouse/models/**'
  pull_request:
    paths:
      - '.github/workflows/visualize-warehouse-changes.yml'
      - 'warehouse/models/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  visualize:
    name: Visualize DAG
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y libgraphviz-dev graphviz graphviz-dev
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: curl -sSL https://install.python-poetry.org | python -
      - uses: google-github-actions/setup-gcloud@v0
        with:
          export_default_credentials: true
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Compile dbt project
        run: |
          cd warehouse
          poetry install
          poetry run dbt deps
          poetry run dbt compile --target prod
      - uses: iterative/setup-cml@v1
      - name: GitHub comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd warehouse
          gsutil cp -r gs://calitp-dbt-artifacts/latest/ .
          echo "# Warehouse report 📦" >> report.md
          echo "## New models 🆕" >> report.md
          poetry run dbt --no-use-colors ls --resource-type model --select state:new --state ./latest | sed "s/calitp_warehouse\.//g" >> report.md
          echo "## Changed models 🛠️" >> report.md
          poetry run dbt --no-use-colors ls --resource-type model --select state:modified --state ./latest | sed "s/calitp_warehouse\.//g" >> report.md
          poetry run dbt --no-use-colors ls --resource-type model --select state:modified --state ./latest | sed 's/^/--include /g' | xargs poetry run python scripts/visualize.py viz man --output=target/dag.png
          echo "" >> report.md
          echo '![](./target/dag.png "Changed models")' >> report.md
          cml comment update report.md
